<a href="https://colab.research.google.com/github/rohit8077/Machine-learning-/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Series**

In [1]:
import pandas as pd
x = [1,2,3,4,5,6,7]

var = pd.Series(x, index =['a','b','c','d','e','f','g'], dtype= "float")

print(var)
print(type(var))
print(var[2])

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    6.0
g    7.0
dtype: float64
<class 'pandas.core.series.Series'>
3.0

/tmp/ipython-input-3687974200.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(var[2])

In [2]:
dic={"name":['Python','C','java'],"Por":[12,13,14,15], "rank":[1,4,3,2]}

var1 = pd.Series(dic)

print(var1)

name    [Python, C, java]
Por      [12, 13, 14, 15]
rank         [1, 4, 3, 2]
dtype: object

In [3]:
s= pd.Series(12, index = [1,2,3,4,5,6,7])
print(s)
print(type(s))

1    12
2    12
3    12
4    12
5    12
6    12
7    12
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
s1 =pd.Series(12, index=[1,2,3,4,5,6,7])
s2 = pd.Series(12, index=[1,2,3,4])
s3 = s1+s2
print(s3)

1    24.0
2    24.0
3    24.0
4    24.0
5     NaN
6     NaN
7     NaN
dtype: float64

***Data Frame***

In [5]:
import pandas as pd
A = [1,2,3,4,5,6]

var = pd.DataFrame(A)

print(var)
print(type(var))

   0
0  1
1  2
2  3
3  4
4  5
5  6
<class 'pandas.core.frame.DataFrame'>

In [6]:
dic = {"A":['Rohit','Sumit','Shaun'],"B":['Khalakpur','Kalan','Sahupur'],"C":[1,2,3],"D":[1,2,3]}

var = pd.DataFrame(dic, columns = ["A","B","C","D"], index = ["a","s","d"])

print(var)
print(type(var))
print(var["A"][2])

       A          B  C  D
a  Rohit  Khalakpur  1  1
s  Sumit      Kalan  2  2
d  Shaun    Sahupur  3  3
<class 'pandas.core.frame.DataFrame'>
Shaun

/tmp/ipython-input-685575860.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(var["A"][2])

In [7]:
list_1 = [[1,2,3,4,5],[11,12,13,14,15]]
var2 =pd.DataFrame(list_1)
print(type(var))
print(var2)

<class 'pandas.core.frame.DataFrame'>
    0   1   2   3   4
0   1   2   3   4   5
1  11  12  13  14  15

In [8]:
sr= {"s": pd.Series([1,2,3,4]), "r":pd.Series([1,2,3,4])}
var2 = pd.DataFrame(sr)
print(type(var2))
print(var2)

<class 'pandas.core.frame.DataFrame'>
   s  r
0  1  1
1  2  2
2  3  3
3  4  4

**Arithmetic Operations**

In [9]:
import pandas as pd
var = pd.DataFrame({"A":[1,2,3,4], "B":[5,6,7,8]})
var

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [10]:
#Adding
var["C"]= var["A"]+var["B"]
var

   A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

In [11]:
#subtracting
var["C"]= var["A"]-var["B"]
var

   A  B  C
0  1  5 -4
1  2  6 -4
2  3  7 -4
3  4  8 -4

In [12]:
#multiplication
var["C"]= var["A"]  * var["B"]
var

   A  B   C
0  1  5   5
1  2  6  12
2  3  7  21
3  4  8  32

In [13]:
#Divide
var["C"]= var["A"]/ var["B"]
var

   A  B         C
0  1  5  0.200000
1  2  6  0.333333
2  3  7  0.428571
3  4  8  0.500000

In [14]:
var1 = pd.DataFrame({"A":[10,20,30,40],"B":[12,13,14,15]})
var1

    A   B
0  10  12
1  20  13
2  30  14
3  40  15

In [15]:
var1["Python"]=var1["A"]<=20
var1["Python1"]=var1["B"]>=15
var1

    A   B  Python  Python1
0  10  12    True    False
1  20  13    True    False
2  30  14   False    False
3  40  15   False     True

**Insert and Delete Function in Python Pandas**

In [16]:
import pandas as pd
Var3 = pd.DataFrame({"A":[1,2,3,4,5],"B":[9,8,7,6,5]})
Var3

   A  B
0  1  9
1  2  8
2  3  7
3  4  6
4  5  5

In [17]:
var.insert(1,"Python1",[11,12,13,14])
var

   A  Python1  B         C
0  1       11  5  0.200000
1  2       12  6  0.333333
2  3       13  7  0.428571
3  4       14  8  0.500000

In [18]:
var["Python12"]= var["A"][:3]
var

   A  Python1  B         C  Python12
0  1       11  5  0.200000       1.0
1  2       12  6  0.333333       2.0
2  3       13  7  0.428571       3.0
3  4       14  8  0.500000       NaN

# **Delete**

In [19]:
var.pop("Python12")
var

   A  Python1  B         C
0  1       11  5  0.200000
1  2       12  6  0.333333
2  3       13  7  0.428571
3  4       14  8  0.500000

# **Write CSV FILE**

In [20]:
import pandas as pd
dis = {"A":[1,2,3,4,5], "B":[2,3,4,5,6],"C":[2,3,5,7,8]}

d = pd.DataFrame(dis)
print(d)

d.to_csv("Test_new.csv")

   A  B  C
0  1  2  2
1  2  3  3
2  3  4  5
3  4  5  7
4  5  6  8

# **Read CSV File**

In [22]:
import pandas as pd
csv_1 = pd.read_csv("/content/silver.crm_sales_details.csv")
csv_1

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [23]:
csv_1 = pd.read_csv("/content/silver.crm_sales_details.csv", nrows=4)

print(type(csv_1))
csv_1

<class 'pandas.core.frame.DataFrame'>

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333

In [25]:
csv_1 = pd.read_csv("/content/silver.crm_sales_details.csv", usecols =["sls_ord_num", "sls_prd_key"])

print(type(csv_1))
csv_1

<class 'pandas.core.frame.DataFrame'>

      sls_ord_num sls_prd_key
0         SO54496     TI-M267
1         SO54496     TT-M928
2         SO54496     PK-7098
3         SO54497     FE-6654
4         SO54497   SO-R809-M
...           ...         ...
60393     SO54494     PK-7098
60394     SO54495     TT-M928
60395     SO54495     HL-U509
60396     SO54495   LJ-0192-L
60397     SO54495     CA-1098

[60398 rows x 2 columns]

In [26]:
csv_1 = pd.read_csv("/content/silver.crm_sales_details.csv", skiprows=[3, 1,2,])

csv_1

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
1,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
2,SO54498,FE-6654,15824,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
3,SO54498,SJ-0194-S,15824,2013-03-16,2013-03-23,2013-03-28,54,1,54,2024-12-30 14:06:36.9733333
4,SO54499,TT-M928,15285,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60390,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60391,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60392,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60393,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60394,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [28]:
csv_2 = pd.read_csv("/content/silver.crm_sales_details.csv", index_col="sls_ord_num")

csv_2

,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
sls_ord_num,,,,,,,,,
SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...
SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [29]:
sv_1 = pd.read_csv("/content/silver.crm_sales_details.csv", header =2)

csv_1

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
1,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
2,SO54498,FE-6654,15824,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
3,SO54498,SJ-0194-S,15824,2013-03-16,2013-03-23,2013-03-28,54,1,54,2024-12-30 14:06:36.9733333
4,SO54499,TT-M928,15285,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60390,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60391,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60392,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60393,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60394,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [30]:
csv_2 = pd.read_csv("/content/silver.crm_sales_details.csv", names=["Col","Rows","Col1","Rows1","Col2","Rows2"])

csv_2

                                                          Col        Rows  \
sls_ord_num sls_prd_key sls_cust_id sls_order_dt  sls_ship_dt  sls_due_dt
SO54496     TI-M267     16399       2013-03-16     2013-03-23  2013-03-28
            TT-M928     16399       2013-03-16     2013-03-23  2013-03-28
            PK-7098     16399       2013-03-16     2013-03-23  2013-03-28
SO54497     FE-6654     20280       2013-03-16     2013-03-23  2013-03-28
...                                                       ...         ...
SO54494     PK-7098     22278       2013-03-16     2013-03-23  2013-03-28
SO54495     TT-M928     14749       2013-03-16     2013-03-23  2013-03-28
            HL-U509     14749       2013-03-16     2013-03-23  2013-03-28
            LJ-0192-L   14749       2013-03-16     2013-03-23  2013-03-28
            CA-1098     14749       2013-03-16     2013-03-23  2013-03-28

                                                       Col1         Rows1  \
sls_ord_num sls_prd_key sls_cust_id sls_order_dt  sls_sales  sls_quantity
SO54496     TI-M267     16399       2013-03-16           25             1
            TT-M928     16399       2013-03-16            5             1
            PK-7098     16399       2013-03-16            2             1
SO54497     FE-6654     20280       2013-03-16           22             1
...                                                     ...           ...
SO54494     PK-7098     22278       2013-03-16            2             1
SO54495     TT-M928     14749       2013-03-16            5             1
            HL-U509     14749       2013-03-16           35             1
            LJ-0192-L   14749       2013-03-16           50             1
            CA-1098     14749       2013-03-16            9             1

                                                       Col2  \
sls_ord_num sls_prd_key sls_cust_id sls_order_dt  sls_price
SO54496     TI-M267     16399       2013-03-16           25
            TT-M928     16399       2013-03-16            5
            PK-7098     16399       2013-03-16            2
SO54497     FE-6654     20280       2013-03-16           22
...                                                     ...
SO54494     PK-7098     22278       2013-03-16            2
SO54495     TT-M928     14749       2013-03-16            5
            HL-U509     14749       2013-03-16           35
            LJ-0192-L   14749       2013-03-16           50
            CA-1098     14749       2013-03-16            9

                                                                        Rows2
sls_ord_num sls_prd_key sls_cust_id sls_order_dt              dwh_create_date
SO54496     TI-M267     16399       2013-03-16    2024-12-30 14:06:36.9733333
            TT-M928     16399       2013-03-16    2024-12-30 14:06:36.9733333
            PK-7098     16399       2013-03-16    2024-12-30 14:06:36.9733333
SO54497     FE-6654     20280       2013-03-16    2024-12-30 14:06:36.9733333
...                                                                       ...
SO54494     PK-7098     22278       2013-03-16    2024-12-30 14:06:36.9733333
SO54495     TT-M928     14749       2013-03-16    2024-12-30 14:06:36.9733333
            HL-U509     14749       2013-03-16    2024-12-30 14:06:36.9733333
            LJ-0192-L   14749       2013-03-16    2024-12-30 14:06:36.9733333
            CA-1098     14749       2013-03-16    2024-12-30 14:06:36.9733333

[60399 rows x 6 columns]

In [31]:
csv_1 = pd.read_csv("/content/silver.crm_sales_details.csv" , dtype={"Marks":"float"})
csv_1

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [32]:
csv_2 = pd.read_csv("/content/silver.crm_sales_details.csv" , header = None)
csv_2

,0,1,2,3,4,5,6,7,8,9
0,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
1,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
2,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
3,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
4,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60394,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60395,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60396,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60397,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60398,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

# **Pandas CSV File Function**

In [33]:
import pandas as pd

csv_11 =pd.read_csv("/content/silver.crm_sales_details.csv")
csv_11

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [34]:
csv_11.index

RangeIndex(start=0, stop=60398, step=1)

In [35]:
csv_11.columns

Index(['sls_ord_num', 'sls_prd_key', 'sls_cust_id', 'sls_order_dt',
       'sls_ship_dt', 'sls_due_dt', 'sls_sales', 'sls_quantity', 'sls_price',
       'dwh_create_date'],
      dtype='object')

In [36]:
csv_11.describe()

        sls_cust_id     sls_sales  sls_quantity     sls_price
count  60398.000000  60398.000000  60398.000000  60398.000000
mean   18841.685420    486.046723      1.000414    486.037783
std     5432.430404    928.450537      0.044011    928.454329
min    11000.000000      2.000000      1.000000      2.000000
25%    14003.000000      8.000000      1.000000      8.000000
50%    18143.000000     30.000000      1.000000     30.000000
75%    23429.750000    540.000000      1.000000    540.000000
max    29483.000000   3578.000000     10.000000   3578.000000

In [37]:
import pandas as pd

csv_12=pd.read_csv("/content/silver.crm_sales_details.csv")
csv_12

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [38]:
csv_12.head(3)

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333

In [39]:
csv_12.tail()

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [40]:
csv_12[2:4]

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333

In [41]:
print(type(csv_12))

<class 'pandas.core.frame.DataFrame'>

In [42]:
csv_12.index.array

<NumpyExtensionArray>
[    np.int64(0),     np.int64(1),     np.int64(2),     np.int64(3),
     np.int64(4),     np.int64(5),     np.int64(6),     np.int64(7),
     np.int64(8),     np.int64(9),
 ...
 np.int64(60388), np.int64(60389), np.int64(60390), np.int64(60391),
 np.int64(60392), np.int64(60393), np.int64(60394), np.int64(60395),
 np.int64(60396), np.int64(60397)]
Length: 60398, dtype: int64

In [43]:
csv_12.sort_index(axis = 0, ascending = False)

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333

In [47]:
csv_1.loc[1, "sls_ord_num"] = "sls_ord_num"

/tmp/ipython-input-555696036.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  csv_1["sls_ord_num"][1] ="sls_ord_num"
/tmp/ipython-input-555696036.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  csv_1["sls_ord_num"][1] ="sls_ord_num"

In [48]:
csv_1.loc[0,"sls_ord_num"]= "SO54495"
csv_1

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54495,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,sls_ord_num,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [49]:
csv_1.loc[:,["sls_ord_num", "sls_prd_key"]]

       sls_ord_num sls_prd_key
0          SO54495     TI-M267
1      sls_ord_num     TT-M928
2          SO54496     PK-7098
3          SO54497     FE-6654
4          SO54497   SO-R809-M
...            ...         ...
60393      SO54494     PK-7098
60394      SO54495     TT-M928
60395      SO54495     HL-U509
60396      SO54495   LJ-0192-L
60397      SO54495     CA-1098

[60398 rows x 2 columns]

In [50]:
csv_1.loc[[7,8],:]

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
7,SO54499,TT-M928,15285,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
8,SO54499,HL-U509-R,15285,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333

In [51]:
csv_1.iloc[1,2]

np.int64(16399)

In [52]:
csv_12=pd.read_csv("/content/silver.crm_sales_details.csv")
csv_12

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [53]:
csv_12.iloc[0,3]

'2013-03-16'

In [54]:
csv_12.drop("sls_ord_num", axis = 1)

,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...
60393,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

# **Handling Missing Data ( Dropena & Fillna)**

In [55]:
import pandas as pd
ad = pd.read_csv("/content/silver.crm_sales_details.csv")
ad

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [56]:
ad.dropna()

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [57]:
ad.dropna(axis=0)

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [58]:
ad.dropna(how ="all")

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [59]:
ad.dropna(inplace=True)
ad

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [60]:
ad.dropna(thresh = 1)

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [61]:
import pandas as pd
aa= pd.read_csv("/content/silver.crm_sales_details.csv")
aa

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [62]:
aa.fillna({"Name":"Rohit Chauhan","Marks": "90.0","Age":"23"})

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [63]:
aa.fillna(method = "ffill") # it's a forword Filling

/tmp/ipython-input-2535539395.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  aa.fillna(method = "ffill") # it's a forword Filling

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [64]:
aa.fillna(method = "bfill") # it's a Backword Filling

/tmp/ipython-input-756932965.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  aa.fillna(method = "bfill") # it's a Backword Filling

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

# **Replace and Interpolate**

In [66]:
aa.replace(to_replace="TI-M267",value ="Rohit")

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,Rohit,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [67]:
aa.replace([1,2,3,4],11)

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,11,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,11,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,11,11,11,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,11,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,11,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,11,11,11,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,11,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,11,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,11,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,11,9,2024-12-30 14:06:36.9733333

In [68]:
aa.replace(1,method ="bfill")

/tmp/ipython-input-3256624551.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  aa.replace(1,method ="bfill")

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,2,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,2,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,2,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,2,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,2,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [69]:
aa.replace(1, method = "ffill",limit = 4)

/tmp/ipython-input-381976757.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  aa.replace(1, method = "ffill",limit = 4)

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [70]:
aa.replace(1, method = "ffill",limit = 4, inplace = True )
aa

/tmp/ipython-input-2574503095.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  aa.replace(1, method = "ffill",limit = 4, inplace = True )

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

# **Interpolate & Replace**

In [71]:
import pandas as pd
qq = pd.read_csv("/content/silver.crm_sales_details.csv")
qq

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [72]:
qq.interpolate()

/tmp/ipython-input-3667807398.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  qq.interpolate()

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [73]:
qq.interpolate(method ='linear',axis = 0)

/tmp/ipython-input-2431242293.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  qq.interpolate(method ='linear',axis = 0)

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [74]:
qq.interpolate(limit_direction = "forward", limit = 1)

/tmp/ipython-input-324052927.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  qq.interpolate(limit_direction = "forward", limit = 1)

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [75]:
qq.interpolate(limit_direction= "both" , limit =2, inplace = True)

/tmp/ipython-input-1680321624.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  qq.interpolate(limit_direction= "both" , limit =2, inplace = True)

In [76]:
qq

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

In [77]:
qq.interpolate(limit_area = "inside")

/tmp/ipython-input-3858854903.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  qq.interpolate(limit_area = "inside")

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price,dwh_create_date
0,SO54496,TI-M267,16399,2013-03-16,2013-03-23,2013-03-28,25,1,25,2024-12-30 14:06:36.9733333
1,SO54496,TT-M928,16399,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
2,SO54496,PK-7098,16399,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
3,SO54497,FE-6654,20280,2013-03-16,2013-03-23,2013-03-28,22,1,22,2024-12-30 14:06:36.9733333
4,SO54497,SO-R809-M,20280,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333
...,...,...,...,...,...,...,...,...,...,...
60393,SO54494,PK-7098,22278,2013-03-16,2013-03-23,2013-03-28,2,1,2,2024-12-30 14:06:36.9733333
60394,SO54495,TT-M928,14749,2013-03-16,2013-03-23,2013-03-28,5,1,5,2024-12-30 14:06:36.9733333
60395,SO54495,HL-U509,14749,2013-03-16,2013-03-23,2013-03-28,35,1,35,2024-12-30 14:06:36.9733333
60396,SO54495,LJ-0192-L,14749,2013-03-16,2013-03-23,2013-03-28,50,1,50,2024-12-30 14:06:36.9733333
60397,SO54495,CA-1098,14749,2013-03-16,2013-03-23,2013-03-28,9,1,9,2024-12-30 14:06:36.9733333

# **Mearging and Concat**

In [78]:
import pandas as pd
as1 = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,9]})
as2 = pd.DataFrame({"A":[1,2,3,5],"C":[15,16,17,18]})

pd.merge(as1,as2, left_index = True, right_index = True , suffixes =("name", "id"))

   Aname  B  Aid   C
0      1  5    1  15
1      2  6    2  16
2      3  7    3  17
3      4  9    5  18

In [79]:
sr1 = pd.Series([1,2,3,4])
sr2 = pd.Series([5,6,7,8])

pd.concat([sr1,sr2])

0    1
1    2
2    3
3    4
0    5
1    6
2    7
3    8
dtype: int64

In [80]:
d1= pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
d2= pd.DataFrame({"A":[1,2,3],"B":[11,12,14]})
pd.concat([d1,d2], axis=1, keys=["d1", "d2"])

  d1      d2
   A  B    A     B
0  1  5  1.0  11.0
1  2  6  2.0  12.0
2  3  7  3.0  14.0
3  4  8  NaN   NaN

# **JOIN**

In [81]:
import pandas as pd

z1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]}, index=["a","b","c","d"])
z2= pd.DataFrame({"C":[10,20,30],"D":[21,22,23]},index=["a","b","c"])
z2.join(z1)

    C   D  A   B
a  10  21  1  11
b  20  22  2  12
c  30  23  3  13

# **Melt()**

In [82]:
import pandas as pd
var = pd.DataFrame({"Days":[1,2,3,4,5,6], "Eng":[10,11,12,13,14,15],"Maths":[17,18,19,20,21,22]})
var

   Days  Eng  Maths
0     1   10     17
1     2   11     18
2     3   12     19
3     4   13     20
4     5   14     21
5     6   15     22

In [83]:
pd.melt(var, id_vars=["Days"], var_name ="Python",value_name = "wscube")

    Days Python  wscube
0      1    Eng      10
1      2    Eng      11
2      3    Eng      12
3      4    Eng      13
4      5    Eng      14
5      6    Eng      15
6      1  Maths      17
7      2  Maths      18
8      3  Maths      19
9      4  Maths      20
10     5  Maths      21
11     6  Maths      22

# **pivot**()

In [84]:
import pandas as pd
var = pd.DataFrame({"days":[1,2,3,4,5,6],
                    "std_name":["a","b","c","a","b","c"],"eng":[10,11,12,13,14,15],"maths":[17,18,19,20,21,22]})
var

   days std_name  eng  maths
0     1        a   10     17
1     2        b   11     18
2     3        c   12     19
3     4        a   13     20
4     5        b   14     21
5     6        c   15     22

In [85]:
var.pivot(index="days", columns="std_name",values="eng")

std_name     a     b     c
days
1         10.0   NaN   NaN
2          NaN  11.0   NaN
3          NaN   NaN  12.0
4         13.0   NaN   NaN
5          NaN  14.0   NaN
6          NaN   NaN  15.0

In [86]:
var.pivot_table(index="std_name",columns="days",aggfunc="sum", margins=True)

           eng                                   maths                    \
days         1     2     3     4     5     6 All     1     2     3     4
std_name
a         10.0   NaN   NaN  13.0   NaN   NaN  23  17.0   NaN   NaN  20.0
b          NaN  11.0   NaN   NaN  14.0   NaN  25   NaN  18.0   NaN   NaN
c          NaN   NaN  12.0   NaN   NaN  15.0  27   NaN   NaN  19.0   NaN
All       10.0  11.0  12.0  13.0  14.0  15.0  75  17.0  18.0  19.0  20.0


days         5     6  All
std_name
a          NaN   NaN   37
b         21.0   NaN   39
c          NaN  22.0   41
All       21.0  22.0  117