<a href="https://colab.research.google.com/github/rohit8077/Machine-learning-/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Series**

In [ ]:
import pandas as pd
x = [1,2,3,4,5,6,7]

var = pd.Series(x, index =['a','b','c','d','e','f','g'], dtype= "float")

print(var)
print(type(var))
print(var[2])

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    6.0
g    7.0
dtype: float64
<class 'pandas.core.series.Series'>
3.0

/tmp/ipython-input-3-3687974200.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(var[2])

In [ ]:
dic={"name":['Python','C','java'],"Por":[12,13,14,15], "rank":[1,4,3,2]}

var1 = pd.Series(dic)

print(var1)

name    [Python, C, java]
Por      [12, 13, 14, 15]
rank         [1, 4, 3, 2]
dtype: object

In [ ]:
s= pd.Series(12, index = [1,2,3,4,5,6,7])
print(s)
print(type(s))

1    12
2    12
3    12
4    12
5    12
6    12
7    12
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
s1 =pd.Series(12, index=[1,2,3,4,5,6,7])
s2 = pd.Series(12, index=[1,2,3,4])
s3 = s1+s2
print(s3)

1    24.0
2    24.0
3    24.0
4    24.0
5     NaN
6     NaN
7     NaN
dtype: float64

***Data Frame***

In [ ]:
import pandas as pd
A = [1,2,3,4,5,6]

var = pd.DataFrame(A)

print(var)
print(type(var))

   0
0  1
1  2
2  3
3  4
4  5
5  6
<class 'pandas.core.frame.DataFrame'>

In [ ]:
dic = {"A":['Rohit','Sumit','Shaun'],"B":['Khalakpur','Kalan','Sahupur'],"C":[1,2,3],"D":[1,2,3]}

var = pd.DataFrame(dic, columns = ["A","B","C","D"], index = ["a","s","d"])

print(var)
print(type(var))
print(var["A"][2])

       A          B  C  D
a  Rohit  Khalakpur  1  1
s  Sumit      Kalan  2  2
d  Shaun    Sahupur  3  3
<class 'pandas.core.frame.DataFrame'>
Shaun

/tmp/ipython-input-8-685575860.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(var["A"][2])

In [ ]:
list_1 = [[1,2,3,4,5],[11,12,13,14,15]]
var2 =pd.DataFrame(list_1)
print(type(var))
print(var2)

<class 'pandas.core.frame.DataFrame'>
    0   1   2   3   4
0   1   2   3   4   5
1  11  12  13  14  15

In [ ]:
sr= {"s": pd.Series([1,2,3,4]), "r":pd.Series([1,2,3,4])}
var2 = pd.DataFrame(sr)
print(type(var2))
print(var2)

<class 'pandas.core.frame.DataFrame'>
   s  r
0  1  1
1  2  2
2  3  3
3  4  4

**Arithmetic Operations**

In [ ]:
import pandas as pd
var = pd.DataFrame({"A":[1,2,3,4], "B":[5,6,7,8]})
var

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [ ]:
#Adding
var["C"]= var["A"]+var["B"]
var

   A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

In [ ]:
#subtracting
var["C"]= var["A"]-var["B"]
var

   A  B  C
0  1  5 -4
1  2  6 -4
2  3  7 -4
3  4  8 -4

In [ ]:
#multiplication
var["C"]= var["A"]  * var["B"]
var

   A  B   C
0  1  5   5
1  2  6  12
2  3  7  21
3  4  8  32

In [ ]:
#Divide
var["C"]= var["A"]/ var["B"]
var

   A  B         C
0  1  5  0.200000
1  2  6  0.333333
2  3  7  0.428571
3  4  8  0.500000

In [ ]:
var1 = pd.DataFrame({"A":[10,20,30,40],"B":[12,13,14,15]})
var1

    A   B
0  10  12
1  20  13
2  30  14
3  40  15

In [ ]:
var1["Python"]=var1["A"]<=20
var1["Python1"]=var1["B"]>=15
var1

    A   B  Python  Python1
0  10  12    True    False
1  20  13    True    False
2  30  14   False    False
3  40  15   False     True

**Insert and Delete Function in Python Pandas**

In [ ]:
import pandas as pd
Var3 = pd.DataFrame({"A":[1,2,3,4,5],"B":[9,8,7,6,5]})
Var3

   A  B
0  1  9
1  2  8
2  3  7
3  4  6
4  5  5

In [ ]:
var.insert(1,"Python1",[11,12,13,14])
var

   A  Python1  B         C
0  1       11  5  0.200000
1  2       12  6  0.333333
2  3       13  7  0.428571
3  4       14  8  0.500000

In [ ]:
var["Python12"]= var["A"][:3]
var

   A  Python1  B         C  Python12
0  1       11  5  0.200000       1.0
1  2       12  6  0.333333       2.0
2  3       13  7  0.428571       3.0
3  4       14  8  0.500000       NaN

# **Delete**

In [ ]:
var.pop("Python12")
var

   A  Python1  B         C
0  1       11  5  0.200000
1  2       12  6  0.333333
2  3       13  7  0.428571
3  4       14  8  0.500000

# **Write CSV FILE**

In [ ]:
import pandas as pd
dis = {"A":[1,2,3,4,5], "B":[2,3,4,5,6],"C":[2,3,5,7,8]}

d = pd.DataFrame(dis)
print(d)

d.to_csv("Test_new.csv")

   A  B  C
0  1  2  2
1  2  3  3
2  3  4  5
3  4  5  7
4  5  6  8

# **Read CSV File**

In [ ]:
import pandas as pd
csv_1 = pd.read_csv("/content/student_dataset (1).csv")
csv_1

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0    NaN         IT   78.0
2        S102  Charlie  22.0      M        ECE    NaN
3        S103    David   NaN      M        NaN   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank   NaN      M        NaN   76.0
6        S106    Grace  22.0      F         CS    NaN
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

In [ ]:
csv_1 = pd.read_csv("/content/student_dataset (1).csv", nrows=4)

print(type(csv_1))
csv_1

<class 'pandas.core.frame.DataFrame'>

  Student_ID     Name   Age Gender Department  Marks
0       S100    Alice  20.0      F         CS   85.0
1       S101      Bob  21.0    NaN         IT   78.0
2       S102  Charlie  22.0      M        ECE    NaN
3       S103    David   NaN      M        NaN   88.0

In [ ]:
csv_1 = pd.read_csv("/content/student_dataset (1).csv", usecols =["Student_ID", "Name"])

print(type(csv_1))
csv_1

<class 'pandas.core.frame.DataFrame'>

   Student_ID     Name
0        S100    Alice
1        S101      Bob
2        S102  Charlie
3        S103    David
4        S104      Eva
5        S105    Frank
6        S106    Grace
7        S107    Henry
8        S108      Ivy
9        S109     Jack
10       S110    Karen
11       S111      Leo
12       S112     Mona
13       S113     Nick
14       S114   Olivia
15       S115     Paul
16       S116   Quincy
17       S117   Rachel
18       S118    Steve
19       S119     Tina

In [ ]:
csv_1 = pd.read_csv("/content/student_dataset (1).csv", skiprows=[3, 1,2,])

csv_1

   Student_ID    Name   Age Gender Department  Marks
0        S103   David   NaN      M        NaN   88.0
1        S104     Eva  23.0      F         IT   92.0
2        S105   Frank   NaN      M        NaN   76.0
3        S106   Grace  22.0      F         CS    NaN
4        S107   Henry  20.0      M         IT   79.0
5        S108     Ivy  21.0      F        ECE   95.0
6        S109    Jack  22.0      M         CS   84.0
7        S110   Karen  23.0      F         IT   88.0
8        S111     Leo  20.0      M        ECE   80.0
9        S112    Mona  21.0      F         CS   91.0
10       S113    Nick  22.0      M         IT   77.0
11       S114  Olivia  23.0      F        ECE   89.0
12       S115    Paul  20.0      M         CS   86.0
13       S116  Quincy  21.0      M         IT   83.0
14       S117  Rachel  22.0      F        ECE   90.0
15       S118   Steve  23.0      M         CS   87.0
16       S119    Tina  20.0      F         IT   93.0

In [ ]:
csv_2 = pd.read_csv("/content/student_dataset (1).csv", index_col="Student_ID")

csv_2

               Name   Age Gender Department  Marks
Student_ID
S100          Alice  20.0      F         CS   85.0
S101            Bob  21.0    NaN         IT   78.0
S102        Charlie  22.0      M        ECE    NaN
S103          David   NaN      M        NaN   88.0
S104            Eva  23.0      F         IT   92.0
S105          Frank   NaN      M        NaN   76.0
S106          Grace  22.0      F         CS    NaN
S107          Henry  20.0      M         IT   79.0
S108            Ivy  21.0      F        ECE   95.0
S109           Jack  22.0      M         CS   84.0
S110          Karen  23.0      F         IT   88.0
S111            Leo  20.0      M        ECE   80.0
S112           Mona  21.0      F         CS   91.0
S113           Nick  22.0      M         IT   77.0
S114         Olivia  23.0      F        ECE   89.0
S115           Paul  20.0      M         CS   86.0
S116         Quincy  21.0      M         IT   83.0
S117         Rachel  22.0      F        ECE   90.0
S118          Steve  23.0      M         CS   87.0
S119           Tina  20.0      F         IT   93.0

In [ ]:
sv_1 = pd.read_csv("/content/student_dataset (1).csv", header =2)

csv_1

   Student_ID    Name   Age Gender Department  Marks
0        S103   David   NaN      M        NaN   88.0
1        S104     Eva  23.0      F         IT   92.0
2        S105   Frank   NaN      M        NaN   76.0
3        S106   Grace  22.0      F         CS    NaN
4        S107   Henry  20.0      M         IT   79.0
5        S108     Ivy  21.0      F        ECE   95.0
6        S109    Jack  22.0      M         CS   84.0
7        S110   Karen  23.0      F         IT   88.0
8        S111     Leo  20.0      M        ECE   80.0
9        S112    Mona  21.0      F         CS   91.0
10       S113    Nick  22.0      M         IT   77.0
11       S114  Olivia  23.0      F        ECE   89.0
12       S115    Paul  20.0      M         CS   86.0
13       S116  Quincy  21.0      M         IT   83.0
14       S117  Rachel  22.0      F        ECE   90.0
15       S118   Steve  23.0      M         CS   87.0
16       S119    Tina  20.0      F         IT   93.0

In [ ]:
csv_2 = pd.read_csv("/content/student_dataset (1).csv", names=["Col","Rows","Col1","Rows1","Col2","Rows2"])

csv_2

           Col     Rows Col1   Rows1        Col2  Rows2
0   Student_ID     Name  Age  Gender  Department  Marks
1         S100    Alice   20       F          CS     85
2         S101      Bob   21     NaN          IT     78
3         S102  Charlie   22       M         ECE    NaN
4         S103    David  NaN       M         NaN     88
5         S104      Eva   23       F          IT     92
6         S105    Frank  NaN       M         NaN     76
7         S106    Grace   22       F          CS    NaN
8         S107    Henry   20       M          IT     79
9         S108      Ivy   21       F         ECE     95
10        S109     Jack   22       M          CS     84
11        S110    Karen   23       F          IT     88
12        S111      Leo   20       M         ECE     80
13        S112     Mona   21       F          CS     91
14        S113     Nick   22       M          IT     77
15        S114   Olivia   23       F         ECE     89
16        S115     Paul   20       M          CS     86
17        S116   Quincy   21       M          IT     83
18        S117   Rachel   22       F         ECE     90
19        S118    Steve   23       M          CS     87
20        S119     Tina   20       F          IT     93

In [ ]:
csv_1 = pd.read_csv("/content/student_dataset (1).csv" , dtype={"Marks":"float"})
csv_1

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0    NaN         IT   78.0
2        S102  Charlie  22.0      M        ECE    NaN
3        S103    David   NaN      M        NaN   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank   NaN      M        NaN   76.0
6        S106    Grace  22.0      F         CS    NaN
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

In [ ]:
csv_2 = pd.read_csv("/content/student_dataset (1).csv" , header = None)
csv_2

             0        1    2       3           4      5
0   Student_ID     Name  Age  Gender  Department  Marks
1         S100    Alice   20       F          CS     85
2         S101      Bob   21     NaN          IT     78
3         S102  Charlie   22       M         ECE    NaN
4         S103    David  NaN       M         NaN     88
5         S104      Eva   23       F          IT     92
6         S105    Frank  NaN       M         NaN     76
7         S106    Grace   22       F          CS    NaN
8         S107    Henry   20       M          IT     79
9         S108      Ivy   21       F         ECE     95
10        S109     Jack   22       M          CS     84
11        S110    Karen   23       F          IT     88
12        S111      Leo   20       M         ECE     80
13        S112     Mona   21       F          CS     91
14        S113     Nick   22       M          IT     77
15        S114   Olivia   23       F         ECE     89
16        S115     Paul   20       M          CS     86
17        S116   Quincy   21       M          IT     83
18        S117   Rachel   22       F         ECE     90
19        S118    Steve   23       M          CS     87
20        S119     Tina   20       F          IT     93

# **Pandas CSV File Function**

In [ ]:
import pandas as pd

csv_11 =pd.read_csv("/content/student_dataset (1).csv")
csv_11

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0    NaN         IT   78.0
2        S102  Charlie  22.0      M        ECE    NaN
3        S103    David   NaN      M        NaN   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank   NaN      M        NaN   76.0
6        S106    Grace  22.0      F         CS    NaN
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

In [ ]:
csv_11.index

RangeIndex(start=0, stop=20, step=1)

In [ ]:
csv_11.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Department', 'Marks'], dtype='object')

In [ ]:
csv_11.describe()

             Age      Marks
count  18.000000  18.000000
mean   21.444444  85.611111
std     1.149026   5.771521
min    20.000000  76.000000
25%    20.250000  80.750000
50%    21.500000  86.500000
75%    22.000000  89.750000
max    23.000000  95.000000

In [ ]:
import pandas as pd

csv_12=pd.read_csv("/content/student_dataset (1).csv")
csv_12

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0    NaN         IT   78.0
2        S102  Charlie  22.0      M        ECE    NaN
3        S103    David   NaN      M        NaN   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank   NaN      M        NaN   76.0
6        S106    Grace  22.0      F         CS    NaN
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

In [ ]:
csv_12.head(3)

  Student_ID     Name   Age Gender Department  Marks
0       S100    Alice  20.0      F         CS   85.0
1       S101      Bob  21.0    NaN         IT   78.0
2       S102  Charlie  22.0      M        ECE    NaN

In [ ]:
csv_12.tail()

   Student_ID    Name   Age Gender Department  Marks
15       S115    Paul  20.0      M         CS   86.0
16       S116  Quincy  21.0      M         IT   83.0
17       S117  Rachel  22.0      F        ECE   90.0
18       S118   Steve  23.0      M         CS   87.0
19       S119    Tina  20.0      F         IT   93.0

In [ ]:
csv_12[2:4]

  Student_ID     Name   Age Gender Department  Marks
2       S102  Charlie  22.0      M        ECE    NaN
3       S103    David   NaN      M        NaN   88.0

In [ ]:
print(type(csv_12))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
csv_12.index.array

<NumpyExtensionArray>
[ np.int64(0),  np.int64(1),  np.int64(2),  np.int64(3),  np.int64(4),
  np.int64(5),  np.int64(6),  np.int64(7),  np.int64(8),  np.int64(9),
 np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14),
 np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19)]
Length: 20, dtype: int64

In [ ]:
csv_12.sort_index(axis = 0, ascending = False)

   Student_ID     Name   Age Gender Department  Marks
19       S119     Tina  20.0      F         IT   93.0
18       S118    Steve  23.0      M         CS   87.0
17       S117   Rachel  22.0      F        ECE   90.0
16       S116   Quincy  21.0      M         IT   83.0
15       S115     Paul  20.0      M         CS   86.0
14       S114   Olivia  23.0      F        ECE   89.0
13       S113     Nick  22.0      M         IT   77.0
12       S112     Mona  21.0      F         CS   91.0
11       S111      Leo  20.0      M        ECE   80.0
10       S110    Karen  23.0      F         IT   88.0
9        S109     Jack  22.0      M         CS   84.0
8        S108      Ivy  21.0      F        ECE   95.0
7        S107    Henry  20.0      M         IT   79.0
6        S106    Grace  22.0      F         CS    NaN
5        S105    Frank   NaN      M        NaN   76.0
4        S104      Eva  23.0      F         IT   92.0
3        S103    David   NaN      M        NaN   88.0
2        S102  Charlie  22.0      M        ECE    NaN
1        S101      Bob  21.0    NaN         IT   78.0
0        S100    Alice  20.0      F         CS   85.0

In [ ]:
csv_1["Student_ID"][1] ="Python"

/tmp/ipython-input-43-1492050434.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  csv_1["Student_ID"][1] ="Python"
/tmp/ipython-input-43-1492050434.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  csv_1["Student_ID"][1] ="Python"

In [ ]:
csv_1.loc[0,"InvoiceID"]= "Python"
csv_1

   Student_ID     Name   Age Gender Department  Marks InvoiceID
0        S100    Alice  20.0      F         CS   85.0    Python
1      Python      Bob  21.0    NaN         IT   78.0       NaN
2        S102  Charlie  22.0      M        ECE    NaN       NaN
3        S103    David   NaN      M        NaN   88.0       NaN
4        S104      Eva  23.0      F         IT   92.0       NaN
5        S105    Frank   NaN      M        NaN   76.0       NaN
6        S106    Grace  22.0      F         CS    NaN       NaN
7        S107    Henry  20.0      M         IT   79.0       NaN
8        S108      Ivy  21.0      F        ECE   95.0       NaN
9        S109     Jack  22.0      M         CS   84.0       NaN
10       S110    Karen  23.0      F         IT   88.0       NaN
11       S111      Leo  20.0      M        ECE   80.0       NaN
12       S112     Mona  21.0      F         CS   91.0       NaN
13       S113     Nick  22.0      M         IT   77.0       NaN
14       S114   Olivia  23.0      F        ECE   89.0       NaN
15       S115     Paul  20.0      M         CS   86.0       NaN
16       S116   Quincy  21.0      M         IT   83.0       NaN
17       S117   Rachel  22.0      F        ECE   90.0       NaN
18       S118    Steve  23.0      M         CS   87.0       NaN
19       S119     Tina  20.0      F         IT   93.0       NaN

In [ ]:
csv_1.loc[:,["Student_ID", "Age"]]

   Student_ID   Age
0        S100  20.0
1      Python  21.0
2        S102  22.0
3        S103   NaN
4        S104  23.0
5        S105   NaN
6        S106  22.0
7        S107  20.0
8        S108  21.0
9        S109  22.0
10       S110  23.0
11       S111  20.0
12       S112  21.0
13       S113  22.0
14       S114  23.0
15       S115  20.0
16       S116  21.0
17       S117  22.0
18       S118  23.0
19       S119  20.0

In [ ]:
csv_1.loc[[7,8],:]

  Student_ID   Name   Age Gender Department  Marks InvoiceID
7       S107  Henry  20.0      M         IT   79.0       NaN
8       S108    Ivy  21.0      F        ECE   95.0       NaN

In [ ]:
csv_1.iloc[1,2]

np.float64(21.0)

In [ ]:
csv_12=pd.read_csv("/content/student_dataset (1).csv")
csv_12

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0    NaN         IT   78.0
2        S102  Charlie  22.0      M        ECE    NaN
3        S103    David   NaN      M        NaN   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank   NaN      M        NaN   76.0
6        S106    Grace  22.0      F         CS    NaN
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

In [ ]:
csv_12.iloc[0,3]

'F'

In [ ]:
csv_12.drop("Student_ID", axis = 1)

       Name   Age Gender Department  Marks
0     Alice  20.0      F         CS   85.0
1       Bob  21.0    NaN         IT   78.0
2   Charlie  22.0      M        ECE    NaN
3     David   NaN      M        NaN   88.0
4       Eva  23.0      F         IT   92.0
5     Frank   NaN      M        NaN   76.0
6     Grace  22.0      F         CS    NaN
7     Henry  20.0      M         IT   79.0
8       Ivy  21.0      F        ECE   95.0
9      Jack  22.0      M         CS   84.0
10    Karen  23.0      F         IT   88.0
11      Leo  20.0      M        ECE   80.0
12     Mona  21.0      F         CS   91.0
13     Nick  22.0      M         IT   77.0
14   Olivia  23.0      F        ECE   89.0
15     Paul  20.0      M         CS   86.0
16   Quincy  21.0      M         IT   83.0
17   Rachel  22.0      F        ECE   90.0
18    Steve  23.0      M         CS   87.0
19     Tina  20.0      F         IT   93.0

# **Handling Missing Data ( Dropena & Fillna)**

In [ ]:
import pandas as pd
ad = pd.read_csv("/content/student_dataset (1).csv")
ad

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0    NaN         IT   78.0
2        S102  Charlie  22.0      M        ECE    NaN
3        S103    David   NaN      M        NaN   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank   NaN      M        NaN   76.0
6        S106    Grace  22.0      F         CS    NaN
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

In [ ]:
ad.dropna()

   Student_ID    Name   Age Gender Department  Marks
0        S100   Alice  20.0      F         CS   85.0
4        S104     Eva  23.0      F         IT   92.0
7        S107   Henry  20.0      M         IT   79.0
8        S108     Ivy  21.0      F        ECE   95.0
9        S109    Jack  22.0      M         CS   84.0
10       S110   Karen  23.0      F         IT   88.0
11       S111     Leo  20.0      M        ECE   80.0
12       S112    Mona  21.0      F         CS   91.0
13       S113    Nick  22.0      M         IT   77.0
14       S114  Olivia  23.0      F        ECE   89.0
15       S115    Paul  20.0      M         CS   86.0
16       S116  Quincy  21.0      M         IT   83.0
17       S117  Rachel  22.0      F        ECE   90.0
18       S118   Steve  23.0      M         CS   87.0
19       S119    Tina  20.0      F         IT   93.0

In [ ]:
ad.dropna(axis=0)

   Student_ID    Name   Age Gender Department  Marks
0        S100   Alice  20.0      F         CS   85.0
4        S104     Eva  23.0      F         IT   92.0
7        S107   Henry  20.0      M         IT   79.0
8        S108     Ivy  21.0      F        ECE   95.0
9        S109    Jack  22.0      M         CS   84.0
10       S110   Karen  23.0      F         IT   88.0
11       S111     Leo  20.0      M        ECE   80.0
12       S112    Mona  21.0      F         CS   91.0
13       S113    Nick  22.0      M         IT   77.0
14       S114  Olivia  23.0      F        ECE   89.0
15       S115    Paul  20.0      M         CS   86.0
16       S116  Quincy  21.0      M         IT   83.0
17       S117  Rachel  22.0      F        ECE   90.0
18       S118   Steve  23.0      M         CS   87.0
19       S119    Tina  20.0      F         IT   93.0

In [ ]:
ad.dropna(how ="all")

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0    NaN         IT   78.0
2        S102  Charlie  22.0      M        ECE    NaN
3        S103    David   NaN      M        NaN   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank   NaN      M        NaN   76.0
6        S106    Grace  22.0      F         CS    NaN
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

In [ ]:
ad.dropna(inplace=True)
ad

   Student_ID    Name   Age Gender Department  Marks
0        S100   Alice  20.0      F         CS   85.0
4        S104     Eva  23.0      F         IT   92.0
7        S107   Henry  20.0      M         IT   79.0
8        S108     Ivy  21.0      F        ECE   95.0
9        S109    Jack  22.0      M         CS   84.0
10       S110   Karen  23.0      F         IT   88.0
11       S111     Leo  20.0      M        ECE   80.0
12       S112    Mona  21.0      F         CS   91.0
13       S113    Nick  22.0      M         IT   77.0
14       S114  Olivia  23.0      F        ECE   89.0
15       S115    Paul  20.0      M         CS   86.0
16       S116  Quincy  21.0      M         IT   83.0
17       S117  Rachel  22.0      F        ECE   90.0
18       S118   Steve  23.0      M         CS   87.0
19       S119    Tina  20.0      F         IT   93.0

In [ ]:
ad.dropna(thresh = 1)

   Student_ID    Name   Age Gender Department  Marks
0        S100   Alice  20.0      F         CS   85.0
4        S104     Eva  23.0      F         IT   92.0
7        S107   Henry  20.0      M         IT   79.0
8        S108     Ivy  21.0      F        ECE   95.0
9        S109    Jack  22.0      M         CS   84.0
10       S110   Karen  23.0      F         IT   88.0
11       S111     Leo  20.0      M        ECE   80.0
12       S112    Mona  21.0      F         CS   91.0
13       S113    Nick  22.0      M         IT   77.0
14       S114  Olivia  23.0      F        ECE   89.0
15       S115    Paul  20.0      M         CS   86.0
16       S116  Quincy  21.0      M         IT   83.0
17       S117  Rachel  22.0      F        ECE   90.0
18       S118   Steve  23.0      M         CS   87.0
19       S119    Tina  20.0      F         IT   93.0

In [ ]:
import pandas as pd
aa= pd.read_csv("/content/student_dataset (1).csv")
aa

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0    NaN         IT   78.0
2        S102  Charlie  22.0      M        ECE    NaN
3        S103    David   NaN      M        NaN   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank   NaN      M        NaN   76.0
6        S106    Grace  22.0      F         CS    NaN
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

In [ ]:
aa.fillna({"Name":"Rohit Chauhan","Marks": "90.0","Age":"23"})

   Student_ID     Name   Age Gender Department Marks
0        S100    Alice  20.0      F         CS  85.0
1        S101      Bob  21.0    NaN         IT  78.0
2        S102  Charlie  22.0      M        ECE  90.0
3        S103    David    23      M        NaN  88.0
4        S104      Eva  23.0      F         IT  92.0
5        S105    Frank    23      M        NaN  76.0
6        S106    Grace  22.0      F         CS  90.0
7        S107    Henry  20.0      M         IT  79.0
8        S108      Ivy  21.0      F        ECE  95.0
9        S109     Jack  22.0      M         CS  84.0
10       S110    Karen  23.0      F         IT  88.0
11       S111      Leo  20.0      M        ECE  80.0
12       S112     Mona  21.0      F         CS  91.0
13       S113     Nick  22.0      M         IT  77.0
14       S114   Olivia  23.0      F        ECE  89.0
15       S115     Paul  20.0      M         CS  86.0
16       S116   Quincy  21.0      M         IT  83.0
17       S117   Rachel  22.0      F        ECE  90.0
18       S118    Steve  23.0      M         CS  87.0
19       S119     Tina  20.0      F         IT  93.0

In [ ]:
aa.fillna(method = "ffill") # it's a forword Filling

/tmp/ipython-input-59-2535539395.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  aa.fillna(method = "ffill") # it's a forword Filling

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0      F         IT   78.0
2        S102  Charlie  22.0      M        ECE   78.0
3        S103    David  22.0      M        ECE   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank  23.0      M         IT   76.0
6        S106    Grace  22.0      F         CS   76.0
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

In [ ]:
aa.fillna(method = "bfill") # it's a Backword Filling

/tmp/ipython-input-60-756932965.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  aa.fillna(method = "bfill") # it's a Backword Filling

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0      M         IT   78.0
2        S102  Charlie  22.0      M        ECE   88.0
3        S103    David  23.0      M         IT   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank  22.0      M         CS   76.0
6        S106    Grace  22.0      F         CS   79.0
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

# **Replace and Interpolate**

In [ ]:
aa.replace(to_replace="Alice",value ="Rohit")

   Student_ID     Name   Age Gender Department  Marks
0        S100    Rohit  20.0      F         CS   85.0
1        S101      Bob  21.0    NaN         IT   78.0
2        S102  Charlie  22.0      M        ECE    NaN
3        S103    David   NaN      M        NaN   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank   NaN      M        NaN   76.0
6        S106    Grace  22.0      F         CS    NaN
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

In [ ]:
aa.replace([1,2,3,4],11)

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0    NaN         IT   78.0
2        S102  Charlie  22.0      M        ECE    NaN
3        S103    David   NaN      M        NaN   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank   NaN      M        NaN   76.0
6        S106    Grace  22.0      F         CS    NaN
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

In [ ]:
aa.replace(1,method ="bfill")

/tmp/ipython-input-63-3256624551.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  aa.replace(1,method ="bfill")

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0    NaN         IT   78.0
2        S102  Charlie  22.0      M        ECE    NaN
3        S103    David   NaN      M        NaN   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank   NaN      M        NaN   76.0
6        S106    Grace  22.0      F         CS    NaN
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

In [ ]:
aa.replace(1, method = "ffill",limit = 4)

/tmp/ipython-input-64-381976757.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  aa.replace(1, method = "ffill",limit = 4)

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0    NaN         IT   78.0
2        S102  Charlie  22.0      M        ECE    NaN
3        S103    David   NaN      M        NaN   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank   NaN      M        NaN   76.0
6        S106    Grace  22.0      F         CS    NaN
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

In [ ]:
aa.replace(1, method = "ffill",limit = 4, inplace = True )
aa

/tmp/ipython-input-65-2574503095.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  aa.replace(1, method = "ffill",limit = 4, inplace = True )

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0    NaN         IT   78.0
2        S102  Charlie  22.0      M        ECE    NaN
3        S103    David   NaN      M        NaN   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank   NaN      M        NaN   76.0
6        S106    Grace  22.0      F         CS    NaN
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

# **Interpolate & Replace**

In [ ]:
import pandas as pd
qq = pd.read_csv("/content/student_dataset (1).csv")
qq

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0    NaN         IT   78.0
2        S102  Charlie  22.0      M        ECE    NaN
3        S103    David   NaN      M        NaN   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank   NaN      M        NaN   76.0
6        S106    Grace  22.0      F         CS    NaN
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

In [ ]:
qq.interpolate()

/tmp/ipython-input-67-3667807398.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  qq.interpolate()

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0    NaN         IT   78.0
2        S102  Charlie  22.0      M        ECE   83.0
3        S103    David  22.5      M        NaN   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank  22.5      M        NaN   76.0
6        S106    Grace  22.0      F         CS   77.5
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

In [ ]:
qq.interpolate(method ='linear',axis = 0)

/tmp/ipython-input-68-2431242293.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  qq.interpolate(method ='linear',axis = 0)

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0    NaN         IT   78.0
2        S102  Charlie  22.0      M        ECE   83.0
3        S103    David  22.5      M        NaN   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank  22.5      M        NaN   76.0
6        S106    Grace  22.0      F         CS   77.5
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

In [ ]:
qq.interpolate(limit_direction = "forward", limit = 1)

/tmp/ipython-input-69-324052927.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  qq.interpolate(limit_direction = "forward", limit = 1)

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0    NaN         IT   78.0
2        S102  Charlie  22.0      M        ECE   83.0
3        S103    David  22.5      M        NaN   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank  22.5      M        NaN   76.0
6        S106    Grace  22.0      F         CS   77.5
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

In [ ]:
qq.interpolate(limit_direction= "both" , limit =2, inplace = True)

/tmp/ipython-input-70-1680321624.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  qq.interpolate(limit_direction= "both" , limit =2, inplace = True)

In [ ]:
qq

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0    NaN         IT   78.0
2        S102  Charlie  22.0      M        ECE   83.0
3        S103    David  22.5      M        NaN   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank  22.5      M        NaN   76.0
6        S106    Grace  22.0      F         CS   77.5
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

In [ ]:
qq.interpolate(limit_area = "inside")

/tmp/ipython-input-72-3858854903.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  qq.interpolate(limit_area = "inside")

   Student_ID     Name   Age Gender Department  Marks
0        S100    Alice  20.0      F         CS   85.0
1        S101      Bob  21.0    NaN         IT   78.0
2        S102  Charlie  22.0      M        ECE   83.0
3        S103    David  22.5      M        NaN   88.0
4        S104      Eva  23.0      F         IT   92.0
5        S105    Frank  22.5      M        NaN   76.0
6        S106    Grace  22.0      F         CS   77.5
7        S107    Henry  20.0      M         IT   79.0
8        S108      Ivy  21.0      F        ECE   95.0
9        S109     Jack  22.0      M         CS   84.0
10       S110    Karen  23.0      F         IT   88.0
11       S111      Leo  20.0      M        ECE   80.0
12       S112     Mona  21.0      F         CS   91.0
13       S113     Nick  22.0      M         IT   77.0
14       S114   Olivia  23.0      F        ECE   89.0
15       S115     Paul  20.0      M         CS   86.0
16       S116   Quincy  21.0      M         IT   83.0
17       S117   Rachel  22.0      F        ECE   90.0
18       S118    Steve  23.0      M         CS   87.0
19       S119     Tina  20.0      F         IT   93.0

# **Mearging and Concat**

In [ ]:
import pandas as pd
as1 = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,9]})
as2 = pd.DataFrame({"A":[1,2,3,5],"C":[15,16,17,18]})

pd.merge(as1,as2, left_index = True, right_index = True , suffixes =("name", "id"))

   Aname  B  Aid   C
0      1  5    1  15
1      2  6    2  16
2      3  7    3  17
3      4  9    5  18

In [ ]:
sr1 = pd.Series([1,2,3,4])
sr2 = pd.Series([5,6,7,8])

pd.concat([sr1,sr2])

0    1
1    2
2    3
3    4
0    5
1    6
2    7
3    8
dtype: int64

In [ ]:
d1= pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
d2= pd.DataFrame({"A":[1,2,3],"B":[11,12,14]})
pd.concat([d1,d2], axis=1, keys=["d1", "d2"])

  d1      d2
   A  B    A     B
0  1  5  1.0  11.0
1  2  6  2.0  12.0
2  3  7  3.0  14.0
3  4  8  NaN   NaN

# **JOIN**

In [ ]:
import pandas as pd

z1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,12,13,14]}, index=["a","b","c","d"])
z2= pd.DataFrame({"C":[10,20,30],"D":[21,22,23]},index=["a","b","c"])
z2.join(z1)

    C   D  A   B
a  10  21  1  11
b  20  22  2  12
c  30  23  3  13

# **Melt()**

In [ ]:
import pandas as pd
var = pd.DataFrame({"Days":[1,2,3,4,5,6], "Eng":[10,11,12,13,14,15],"Maths":[17,18,19,20,21,22]})
var

   Days  Eng  Maths
0     1   10     17
1     2   11     18
2     3   12     19
3     4   13     20
4     5   14     21
5     6   15     22

In [ ]:
pd.melt(var, id_vars=["Days"], var_name ="Python",value_name = "wscube")

    Days Python  wscube
0      1    Eng      10
1      2    Eng      11
2      3    Eng      12
3      4    Eng      13
4      5    Eng      14
5      6    Eng      15
6      1  Maths      17
7      2  Maths      18
8      3  Maths      19
9      4  Maths      20
10     5  Maths      21
11     6  Maths      22

# **pivot**()

In [ ]:
import pandas as pd
var = pd.DataFrame({"days":[1,2,3,4,5,6],
                    "std_name":["a","b","c","a","b","c"],"eng":[10,11,12,13,14,15],"maths":[17,18,19,20,21,22]})
var

   days std_name  eng  maths
0     1        a   10     17
1     2        b   11     18
2     3        c   12     19
3     4        a   13     20
4     5        b   14     21
5     6        c   15     22

In [ ]:
var.pivot(index="days", columns="std_name",values="eng")

std_name     a     b     c
days
1         10.0   NaN   NaN
2          NaN  11.0   NaN
3          NaN   NaN  12.0
4         13.0   NaN   NaN
5          NaN  14.0   NaN
6          NaN   NaN  15.0

In [ ]:
var.pivot_table(index="std_name",columns="days",aggfunc="sum", margins=True)

           eng                                   maths                    \
days         1     2     3     4     5     6 All     1     2     3     4
std_name
a         10.0   NaN   NaN  13.0   NaN   NaN  23  17.0   NaN   NaN  20.0
b          NaN  11.0   NaN   NaN  14.0   NaN  25   NaN  18.0   NaN   NaN
c          NaN   NaN  12.0   NaN   NaN  15.0  27   NaN   NaN  19.0   NaN
All       10.0  11.0  12.0  13.0  14.0  15.0  75  17.0  18.0  19.0  20.0


days         5     6  All
std_name
a          NaN   NaN   37
b         21.0   NaN   39
c          NaN  22.0   41
All       21.0  22.0  117